### PR TITLE
300 presumptions allow and deny

### PR DESCRIPTION
**Pull request by wwitzel**
Implementing Issue #300: replacing presumptions.txt with allowed_presumptions.txt and disallowed_presumptions.txt for each theorem proof for better control with this safeguard against circular logic and less prone to breakage when updating automation features.

### CODE REVIEW

**Comment by wwitzel** [comment]
Hoss, you don't need to look at these changes in detail (there are thousands of changes w.r.t. removed presumptions.txt and added allowed_presumptions.txt and disallowed_presumptions.txt).  Just get a sense for what these changes entail for your own awareness and go ahead with the merger.  Let me know when you do, and I'll update the webpages as soon as I am able.

**Comment by wdcraft01** [comment]
This is looks great and the interactive steps you reviewed for us this past Wednesday 6/28 helped make things clear. It will be interesting to see how this evolves a bit — we might find, as you suggested/alluded to, that we'll welcome some/all of the non-problematic dependencies to be automatically included without the user's active/explicit “OK” each time.

**Review by wdcraft01 — APPROVED** [review]
This is looks great and the interactive steps you reviewed for us this past Wednesday 6/28 helped make things clear. It will be interesting to see how this evolves a bit — we might find, as you suggested, that we'll welcome some/all of the non-problematic dependencies to be automatically included without the user's active/explicit “OK” each time.

**Comment by wwitzel** [comment]
My current leaning is to keep allowances/disallowances explicit and transparent to the user and just indicate when things are known to be safe/unsafe.  It might be a good idea to add an "are you sure?" when the select the option that is contrary to what is known.  If it's too automated, it can thwart that attempts of a user to do something unexpected (maybe it is currently 'known' to be safe/unsafe, but the user is planning changes and should at least be alerted; or maybe they plan to go with the suggested allowance/disallowance but up one or more levels).  Thanks for taking a look and given this some thought, @wdcraft01.

**Pull request merged**
